var that=this;function __skpm_run(t,e){that.context=e;var n=function(t){var e={};function n(o){if(e[o])return e[o].exports;var r=e[o]={i:o,l:!1,exports:{}};return t[o].call(r.exports,r,r.exports,n),r.l=!0,r.exports}return n.m=t,n.c=e,n.d=function(t,e,o){n.o(t,e)||Object.defineProperty(t,e,{enumerable:!0,get:o})},n.r=function(t){"undefined"!=typeof Symbol&&Symbol.toStringTag&&Object.defineProperty(t,Symbol.toStringTag,{value:"Module"}),Object.defineProperty(t,"__esModule",{value:!0})},n.t=function(t,e){if(1&e&&(t=n(t)),8&e)return t;if(4&e&&"object"==typeof t&&t&&t.__esModule)return t;var o=Object.create(null);if(n.r(o),Object.defineProperty(o,"default",{enumerable:!0,value:t}),2&e&&"string"!=typeof t)for(var r in t)n.d(o,r,function(e){return t[e]}.bind(null,r));return o},n.n=function(t){var e=t&&t.__esModule?function(){return t.default}:function(){return t};return n.d(e,"a",e),e},n.o=function(t,e){return Object.prototype.hasOwnProperty.call(t,e)},n.p="",n(n.s="./src/toggle-syncing.js")}({"./src/toggle-syncing.js":
/*!*******************************!*\
  !*** ./src/toggle-syncing.js ***!
  \*******************************/
/*! exports provided: toggleSyncing */function(t,e,n){"use strict";function o(t){return(o="function"==typeof Symbol&&"symbol"==typeof Symbol.iterator?function(t){return typeof t}:function(t){return t&&"function"==typeof Symbol&&t.constructor===Symbol&&t!==Symbol.prototype?"symbol":typeof t})(t)}n.r(e),n.d(e,"toggleSyncing",function(){return c});var r=n(/*! sketch/ui */"sketch/ui"),u=n(/*! sketch/settings */"sketch/settings");function c(t){var e=function(){switch(u.documentSettingForKey(t.document,"trackDocument")){case!0:u.setDocumentSettingForKey(t.document,"trackDocument",!1),t.document.showMessage("Stopped syncing changes for ".concat(t.document.cloudName()));break;default:u.setDocumentSettingForKey(t.document,"trackDocument",!0),t.document.showMessage("Started syncing changes for ".concat(t.document.cloudName()))}};if(void 0!==u.settingForKey("userApplicationToken")||null!=u.settingForKey("userApplicationToken"))console.log(o(u.settingForKey("userApplicationToken"))),console.log(u.settingForKey("userApplicationToken")),e();else{var n=r.getStringFromUser("Enter your Sensive token","");u.setSettingForKey("userApplicationToken",n),e()}}},"sketch/settings":
/*!**********************************!*\
  !*** external "sketch/settings" ***!
  \**********************************/
/*! no static exports found */function(t,e){t.exports=require("sketch/settings")},"sketch/ui":
/*!****************************!*\
  !*** external "sketch/ui" ***!
  \****************************/
/*! no static exports found */function(t,e){t.exports=require("sketch/ui")}});"default"===t&&"function"==typeof n?n(e):n[t](e)}that.toggleSyncing=__skpm_run.bind(this,"toggleSyncing"),that.onRun=__skpm_run.bind(this,"default");